### ISSUE TITLE
Using 'channels_last' layout of batches

### ISSUE THREAD

**Issue by slizzered** [MIC-DKFZ/batchgenerators#31]
Hi!
First of all, thanks for that awesome project. I feel like it will really be an improvement over my current 3D data augmentation, as it offers a nicer (and modular) way to stack multiple transforms with individual probabilities.

My current solution (CNN, data augmentation, and all) is built entirely around a 'channels_last' data layout, where every batch has a shape (b, x, y, z, c). From the code I viewed, it appears that the augmentations of batchgenerators naturally use a (b, c, x, y, z) format.
Is there an elegant way to still keep my data layout and augment it correctly? (Of course, I could transpose my batches in a DataLoader derived from SlimDataLoaderBase and wrap/derive MultiThreadedAugmenter to revert the transposition, but this seems quite heavy-handed to me.)

Best regards,
Carlchristian

**Comment by FabianIsensee** [comment]
Hi,
please pull again from github. I just added ConvertToChannelLastTransform. It is not tested, I just implemented it. So make sure it really does what you need.

I assume you are using channel_last because your deep learning framework requires you to do so? Here is how you can now generate batches in (b, x, y, z, c) with batchgenerators:

1) have your DataLoader return batches in the supported format (b, c, x, y, z)
2) do all your augmentations in (b, c, x, y, z). There is no easy way to make batchgenerators process batches with a different channel ordering
3) the last augmentation in your list must now be ConvertToChannelLastTransform. It will convert batches to (b, x, y, z, c). (EXCEPTION! If you are using NumpyToTensor then ConvertToChannelLastTransform must be before NumpyToTensor)

Let me know if this is what you need.
Best,
Fabian

**Comment by slizzered** [comment]
Hi Fabian,
thanks a lot for your quick response. In principle, my deep learning framework is capable of using both batch layouts, but the way the code and data are currently laid out is (b, x, y, z, c), as it appeared more natural for me when starting the project.

I can confirm that your new transform is performing as expected and I am now able to train a network using batchgenerators :) 
Thank you again for implementing it so quickly, it's a perfect solution!
all the best,
Carlchristian
