### ISSUE TITLE
Can the generators be used to load and preprocess files on the fly?

### ISSUE THREAD

**Issue by jchen42703** [MIC-DKFZ/batchgenerators#9]
From what I've read in the README is that the input data values must be arrays. Is there any functionality that allows me to have the values as a list of filenames so that the generator loads files on the fly (with augmentation)? <br> 
i.e.
```
# getting paths for data 
from glob import glob 
local_train_path = '/content/training/' 
local_label_path = '/content/labels/' 
train_paths = glob(local_train_path + '**.nii', recursive = True) 
mask_paths = glob(local_label_path + '**.nii', recursive = True) 
data_dict = {'data': train_paths, 'seg': `mask_paths}
``` 
Thank you for your time and consideration.

**Comment by FabianIsensee** [comment]
Hi,
the batchgenerators do anything you want them to do. And it is only the Transforms that require arrays. What happens before is up to you. We ourselves use it for many different datasets that are stored differently, which is why we do not provide any code to actually load the data. As a user, you are supposed to do that yourself by deriving from DataLoaderBase and implementing your data loading scheme yourself. Specifically, you at least need to implement the generate_train_batch in your derived class. Here you can use self._data (which is whatever you passed to the init, so it can be an arbitrary data structure such as for example a list of filenames) to load your files.
Best,
Fabian

**Comment by jchen42703** [comment]
Thank you for the quick response! Just to clarify, will the Transforms work as long as the output of the dataloader is a dictionary of arrays?
i.e. 
```
class DataLoader(SlimDataLoaderBase):
     ...
    return {'data': array, 'seg': array}
```

**Comment by FabianIsensee** [comment]
Correct
Best,
Fabian
